site_name: TinyMPC

theme:
  name: material

  icon:
    logo: material/graph-outline
    repo: fontawesome/brands/github

  favicon: images/favicon.ico

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
      
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: tinympc-default

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: tinympc-slate

  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.footer

    - search.suggest
    - search.share

    - header.autohide

plugins:
  - search
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: date

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/watch?v=NKOrRyhcr6w
      name: TinyMPC on YouTube
    - icon: fontawesome/brands/github
      link: https://github.com/TinyMPC/TinyMPC
      name: TinyMPC on GitHub
    - icon: simple/arxiv
      link: https://arxiv.org/abs/2310.16985
      name: TinyMPC on arXiv

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/TinyMPC/TinyMPC
repo_name: TinyMPC

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      
copyright: Copyright &copy; 2024 Robotic Exploration Lab