site_name: TinyMPC

repo_url: https://github.com/TinyMPC/TinyMPC
repo_name: TinyMPC

nav:
  - index.md
  - Get Started:
    - Installation: get-started/installation.md
    - Examples: get-started/examples.md
    - Obtain the model: get-started/model.md
  - The Solver: 
    - Inside TinyMPC: solver/solver.md
    - Background: solver/background.md

theme:
  name: material

  icon:
    logo: fontawesome/solid/microchip
    repo: fontawesome/brands/github
    annotation: material/arrow-right-circle

  favicon: media/favicon.ico

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      # primary: custom
      # primary: tinympc-default

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      # scheme: tinympc-slate
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      # primary: custom
      # primary: tinympc-slate

  features:
    # - navigation.instant # Using navigation.instant disables table of contents auto-highlighting
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.tracking
    - navigation.tabs
    - navigation.sections
    # - navigation.path # Insiders feature
    # - navigation.indexes # Incompatible with toc.integrate
    - navigation.footer
    - navigation.top
    
    - toc.follow
    - toc.integrate
    
    - search.suggest
    - search.share

    # - header.autohide
    
    - content.code.copy
    # - content.code.select # Insiders feature
    - content.code.annotate
    - content.tabs.link

plugins:
  - search
  # - git-revision-date-localized:
  #     enable_creation_date: true
  #     type: date

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/watch?v=NKOrRyhcr6w
      name: TinyMPC on YouTube
    - icon: fontawesome/brands/github
      link: https://github.com/TinyMPC
      name: TinyMPC on GitHub
    - icon: simple/arxiv
      link: https://arxiv.org/abs/2310.16985
      name: TinyMPC on arXiv

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  # Admonitions
  - admonition
  # Formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

extra_javascript:
  - javascript/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  
extra_css:
  - stylesheets/extra.css
      
copyright: Copyright &copy; 2024 Robotic Exploration Lab